version: "3"
services:
  postgres:
    image: docker.io/postgres:16.3-alpine3.20
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test